dist: jammy
language: python

python:
- '3.9'

env:
  global:
  - secure: P/TYBbm9u30RLGrfNVNMm689qOqHJyBniwKITfgPiK3aujeGdT6Z1XDNPYPgwlWKE5kDPSf1ZA3CfTj2rwUOKWfKANeIH7BRLh0n02hIIwAZUiV1u8/5pQk84mDH5UAMtVOwsAbbRof+tvEjjfrr0EmCGnhcbVrXo7f9jIUXiJcRCMdjGgMmmoRu5WQhIyVfK7n+Qr9p84Vml999VFQkiPcmGTrJxbPE6tiTQoWRWc9ak3q/SEmUUP1F31B5FhF74C5B5DKZyq+oEWmzeXe5noleZ0vzW2uy3qupHh2bj+SZC/WcfNRPxMc49Pjc9sa65GgaLsTvww2nQX6Ioycgz7OOiIayJLFOKlvQ4Fahow1zjjUEI4/5y3bL7vhXFLEUn0dxvWXanmWLsO8cmM0NQ/AeXhrd2/2pblVtBVrimzkQydJANgyTCw2E/Wbvxnkxyc5GfttfRKgABJ/mLWNlKQ4RQNhAXmD7CqH9kd7T1+oyiuQTOj6Bu8wN5IsGuqv41k4aufyq5LN+4F9/ugex05NBGtGm6a9byAq7XjOzpvFWoki8kwVIoJie8gA74kUf05iAl0iQVqCMFPrxNyeH2cngZgfi+rs7KhnoJ9ZctqCDHIg75xPt9heskn2pw59VU1tcs1QOmNEynEMsusC/wA/WbBQrx9ppVovqjvCaozg=


install:
  - pip install --upgrade pip
  - sudo apt-get install libssl-dev --upgrade
  - pip install poetry
  - poetry install -vv

script:
  - poetry run pytest -vv
  
before_deploy:
- poetry config pypi-token.pypi $PYPI_API_TOKEN
- poetry build -f sdist

deploy:
  provider: script
  script: poetry publish -n -vv
  skip_cleanup: true
  on:
    tags: true
    repo: uc-cdis/datadictionary
    python: 3.9

after_deploy:
- pip install gen3git
- gen3git release
