[tool.poetry]
name = "gen3Dictionary"
version = "2.0.5"
description = ""
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "gdcdictionary"}]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "*"
jsonschema = "*"
dictionaryutils = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = ">=7.3.2"
pytest-cov = ">=4.1.0"
isort = ">=5.12.0"
black = ">=23.10.0"
pylint = ">=3.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"
