$schema: "http://json-schema.org/draft-04/schema#"

id: "staging"
title: Staging
type: object
namespace: http://cri.uchicago.edu/
category: clinical
program: '*'
project: '*'
description: "Staging"
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - created_datetime
  - updated_datetime
  - state

links:
  - name: subjects
    backref: stagings 
    label: of
    target_type: subject
    multiplicity: many_to_one    
    required: true
  - name: timings
    backref: stagings
    label: part_of
    target_type: timing
    multiplicity: many_to_one
    required: false

required:
  - submitter_id
  - subjects

uniqueKeys:
  - [ id ]
  - [ project_id, submitter_id ]

properties:
  type:
    description: "Default system-assigned property for each node"
    enum: [ "staging" ]
  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
  submitter_id:
    description: "PCDC internal ID"
    type:
      - string
  age_at_staging:
    description: "Age of the subject (in days) at staging assessment"
    type:
      - number
  stage_system:
    description: ""
    enum: 
      - FIGO
      - COG
      - AJCC
      - INSS
      - INRGSS
      - EVANS
      - Ann Arbor
      - Unknown
      - Not Reported
  stage:
    description: ""
    enum: 
      - Stage I
      - Stage IA
      - Stage IB
      - Stage IS
      - Stage II
      - Stage IIA
      - Stage IIB
      - Stage IIC
      - Stage III
      - Stage IIIA
      - Stage IIIB
      - Stage IIIC
      - Stage IV
      - Stage IVs
      - Stage 0
      - Stage 1
      - Stage 2a
      - Stage 2b
      - Stage 3
      - Stage 4
      - Stage 4s
      - Stage L1
      - Stage L2
      - Stage M
      - Stage MS
      - Unknown
      - Not Reported
  AB:
    description: "HL Ann Arbor A vs B Staging Designation" 
    enum: 
      - A
      - B
      - Unknown
      - Not Reported
  E:
    description: "HL Ann Arbor E Staging Designation" 
    enum:
      - "Y"
      - "N"
      - Unknown
      - Not Reported
  S:
    description: "HL Ann Arbor S Staging Designation" 
    enum:
      - "Y"
      - "N"
      - Unknown
      - Not Reported
  tnm_finding:
    description: "TNM finding" 
    enum:
      - "Favorable Site, M0"
      - "Other Site, any T, a, N0, M0"
      - "Other Site, any T, a, N1, M0, any T, b, N0/N1, M0"
      - "Metastases, M1"
      - Unknown
      - Not reported
  irs_group:
    description: "IRS Surgical-Pathologic Grouping System"
    enum:
      - Group I
      - Group IIA
      - Group IIB
      - Group IIC
      - Group II, NOS
      - Group III
      - Group IV
      - Unknown
      - Not reported


  

  timings:
    $ref: "_definitions.yaml#/to_one" 
  subjects:
    $ref: "_definitions.yaml#/to_one"  
  project_id:
    $ref: "_definitions.yaml#/project_id"
  created_datetime:
    $ref: "_definitions.yaml#/datetime"
  updated_datetime:
    $ref: "_definitions.yaml#/datetime"

  state:
    $ref: "_definitions.yaml#/state"

