$schema: "http://json-schema.org/draft-04/schema#"

id: "staging"
title: Staging
type: object
namespace: http://cri.uchicago.edu/
category: administrative
program: '*'
project: '*'
description: "Staging"
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - created_datetime
  - updated_datetime
  - state

links:
  - name: clinical_events
    backref: stagings
    label: part of
    target_type: clinical_event
    multiplicity: many_to_one
    required: true

required:
  - submitter_id
  - clinical_events

uniqueKeys:
  - [ id ]
  - [ project_id, submitter_id ]

properties:
  type:
    enum: [ "staging" ]
  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
  submitter_id:
    type:
      - string
      - "null"
  tnm_finding:
    enum:
      - "Favorable Site, M0"
      - "Other site, any T, a, N0, M0"
      - "Other site, any T, a, N1, M0, any T, b, N0/N1, M0"
      - "Metastases, ML"
      - Unknown
      - Not reported
  irs_group:
    description: "IRS Surgical-Pathologic Grouping System"
    enum:
      - Group I
      - Group IIA
      - Group IIB
      - Group IIC
      - Group II, NOS
      - Group III
      - Group IV
      - Unknown
      - Not reported


  

  clinical_events:
    $ref: "_definitions.yaml#/to_one"   
  project_id:
    $ref: "_definitions.yaml#/project_id"
  created_datetime:
    $ref: "_definitions.yaml#/datetime"
  updated_datetime:
    $ref: "_definitions.yaml#/datetime"

  state:
    $ref: "_definitions.yaml#/state"

